# Labeler configuration
# See: https://github.com/actions/labeler

# Documentation
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

# CI/CD
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

# Configuration
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.toml"
          - "**/*.yaml"
          - "**/*.yml"
          - "!.github/**/*"

# Dependencies
area/deps:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Cargo.toml"
          - "**/Cargo.lock"

# Testing
area/testing:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tests/**/*"
          - "**/*_test.rs"
          - "**/*_tests.rs"

# Authn crate
area/authn:
  - changed-files:
      - any-glob-to-any-file:
          - "crates/authn/**/*"

# Storage crate
area/storage:
  - changed-files:
      - any-glob-to-any-file:
          - "crates/storage/**/*"

# Storage-ledger crate
area/storage-ledger:
  - changed-files:
      - any-glob-to-any-file:
          - "crates/storage-ledger/**/*"
